######
##
# 1) start: docker-compose -f docker-compose-prod.yml up -d
# 2) attach: docker attach ...
# 3) detach: detach with <CTRL-p> <CTRL-q>
# 4) stop: docker-compose down
# VISIT localhost:8080/
##
######
version: '2.3'

networks:
  anet:

services:

  # BEGIN: FRONTEND
  frontend:
    image: bigabig/mbot-frontend:latest
    container_name: frontend
    ports:
      - 8080:8080
    depends_on:
      keywords:
        condition: service_healthy
      ner:
        condition: service_healthy
      textrank:
        condition: service_healthy
    networks:
      - anet
  # END: FRONTEND

  # BEGIN: KEYWORDS
  keywords:
    image: bigabig/mbot-keyterms:latest
    container_name: keywords
    ports:
      - 8888:8080
    healthcheck:
      test: curl 0.0.0.0:8080/healthcheck
      interval: 10s
      timeout: 10s
      retries: 30
    networks:
      - anet
  # END: KEYWORDS

  # BEGIN: NER
  ner:
    image: bigabig/mbot-ner:latest
    container_name: ner
    ports:
      - 9000:9000
    healthcheck:
      test: curl 0.0.0.0:9000/de && curl 0.0.0.0:9000/en
      interval: 10s
      timeout: 10s
      retries: 30
    depends_on:
      keywords:
        condition: service_healthy
    networks:
      - anet
  # END: NER

  # BEGIN: TEXTRANK
  textrank:
    image: bigabig/mbot-textrank:latest
    container_name: textrank
    ports:
      - 9001:5000
    healthcheck:
      test: curl 0.0.0.0:5000
      interval: 10s
      timeout: 10s
      retries: 30
    depends_on:
      keywords:
        condition: service_healthy
      ner:
        condition: service_healthy
    networks:
      - anet
  # END: TEXTRANK
