######
##
# 1) start: docker-compose -f docker-compose-prod.yml up -d
# 2) attach: docker attach ...
# 3) detach: detach with <CTRL-p> <CTRL-q>
# 4) stop: docker-compose down
# VISIT localhost:8080/
##
######
version: '2.3'

networks:
  anet:

services:

  # BEGIN: FRONTEND
  frontend:
    image: bigabig/mbot-frontend:latest
    ports:
      - 8080:8080
    networks:
      - anet
  # END: FRONTEND

  # BEGIN: KEYWORDS
  keywords:
    image: bigabig/mbot-keyterms:latest
    ports:
      - 8888:8080
    networks:
      - anet
  # END: KEYWORDS

  # BEGIN: NER
  ner:
    image: bigabig/mbot-ner:latest
    ports:
      - 9000:9000
    networks:
      - anet
  # END: NER

  # BEGIN: TEXTRANK
  textrank:
    image: bigabig/mbot-textrank:latest
    ports:
      - 9001:5000
    networks:
      - anet
  # END: TEXTRANK
