######
##
# 1) start: docker-compose docker-compose up -d <services>
# 2) attach: docker attach ...
# 3) detach: detach with <CTRL-p> <CTRL-q>
# 4) stop: docker-compose down
##
######
version: '2.3'

networks:
  anet:

services:

  # BEGIN: KEYWORDS
  keywords:
    image: bigabig/mbot-keyterms:latest
    ports:
      - 8888:8080
    healthcheck:
      test: curl 0.0.0.0:8080/swagger-ui.html
      interval: 10s
      timeout: 5s
      retries: 30
    networks:
      - anet
  # END: KEYWORDS

  # BEGIN: NER
  ner:
    image: bigabig/mbot-ner:latest
    ports:
      - 9000:9000
    healthcheck:
      test: curl 0.0.0.0:9000/de && curl 0.0.0.0:9000/en
      interval: 10s
      timeout: 5s
      retries: 30
    networks:
      - anet
  # END: NER

  # BEGIN: TEXTRANK
  textrank:
    image: bigabig/mbot-textrank:latest
    ports:
      - 9001:5000
    healthcheck:
      test: curl 0.0.0.0:5000
      interval: 10s
      timeout: 5s
      retries: 30
    networks:
      - anet
  # END: TEXTRANK

  # BEGIN: CLSUMM
  clsumm:
    image: bigabig/mbot-clsumm:latest
    ports:
      - 9002:5000
    healthcheck:
      test: curl 0.0.0.0:5000
      interval: 10s
      timeout: 5s
      retries: 30
    networks:
      - anet
  # END: CLSUMM
